# To use:
#
#   $ micromamba create -f environment.yml
#   $ micromamba activate dseams
#
name: dseams
channels:
  - conda-forge
dependencies:
  - compilers
  - gfortran
  - catch2
  - yaml-cpp
  - liblapack
  - libblas
  - boost-cpp
  - cmake
  - meson
  - cmake
  # - lua-luafilesystem
  - luarocks
  # Pinned
  - fmt==9.0.0
  - eigen==3.4.0
  - lua==5.4.4
